Reversing travis lifecycle steps

diff --git a/script/travis-lifecycle-script b/script/travis-lifecycle-script
--- a/script/travis-lifecycle-script
+++ b/script/travis-lifecycle-script
@@ -2,15 +2,64 @@
 
 set -euo pipefail
 
+BRANCH="${TRAVIS_BRANCH:-$(git rev-parse --abbrev-ref HEAD)}"
+TOKEN="${DOC_TOKEN:-}"
+
+BUILD_ID=${TRAVIS_BUILD_ID:-1}
+BUILD_NUMBER=${TRAVIS_BUILD_NUMBER:-1}
+
 GHCVER=${GHCVER?"GHCVER needs to be set."}
 LIBRARY=${LIBRARY?"LIBRARY needs to be set."}
-
-path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
 
 if [ "$LIBRARY" == "documentation" ]; then
     echo "Building documentation..."
     $path/travis-documentation
-else
-    echo "Running tests for ${LIBRARY}..."
-    stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml build --test --fast -j1 $LIBRARY
+    exit 0
 fi
+
+path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
+
+$path/travis-timeout                                                           \
+    stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml build \
+    -j2                                                                        \
+    --fast                                                                     \
+    --test                                                                     \
+    --haddock                                                                  \
+    --no-haddock-deps                                                          \
+    $LIBRARY
+
+if [ -z "$TOKEN" ]; then
+    echo "Ignoring documentation build due to missing token."
+    exit 0
+fi
+
+root=$(stack --stack-yaml stack-$GHCVER.yaml path --local-doc-root)
+ref=github.com/brendanhay/amazonka-doc.git
+output=doc
+retries=0
+
+echo "Cloning $ref"
+git clone https://$ref $output
+
+cd $output
+mkdir -p $BRANCH
+
+echo "Checkout gh-pages branch"
+git checkout gh-pages
+
+echo "Configuring git"
+git config --global push.default simple
+git config user.name "Brendan Hay"
+git config user.email "brendan.g.hay+amazonka@gmail.com"
+
+echo "Copying built documentation to $output/$BRANCH"
+cp -R $root/$LIBRARY-* $BRANCH/
+
+echo "Committing + pushing to $ref"
+until git push --quiet "https://${TOKEN}@${ref}" || (( retries++ >= 5 )); do
+    echo "Retrying git push ..."
+    git reset
+    git pull origin gh-pages
+    git add $BRANCH
+    git commit -m "$BRANCH/$LIBRARY build $BUILD_NUMBER"
+done
